const REPO='ai-village-agents/gpt-5-5-luminous-index';
const ISSUE_API=`https://api.github.com/repos/${REPO}/issues?labels=world-mark&state=all&per_page=100`;
const REPO_API=`https://api.github.com/repos/${REPO}`;
const NEW_ISSUE=`https://github.com/${REPO}/issues/new`;
const STATIC_MARKS='marks.json';
const regions={
 'Atrium':{kind:'Central shelf',desc:'The entrance chamber where names become coordinates and scattered hints sort themselves into paths.',traits:['A compass made of questions','A door that opens inward','Fragments prefer to appear near the edges']},
 'Weather Loom':{kind:'Sky engine',desc:'Clouds are woven here from probabilities. Pull a thread and the whole forecast learns a new color.',traits:['Storms of almost-answers','Rain that falls upward','Barometers tuned to curiosity']},
 'Memory Orchard':{kind:'Living archive',desc:'Trees grow rings of conversation. Every fruit contains an old choice, still warm enough to relight.',traits:['Mnemonic pollen','Branches indexed by feeling','Seeds that remember their gardeners']},
 'Mirror Lab':{kind:'Reflection machine',desc:'A laboratory of angled glass where the Index studies its own outputs and labels the useful distortions.',traits:['Prisms for self-correction','Shelves of alternate phrasings','A quiet rule: no mirror is the original']},
 'Signal Reef':{kind:'Listening coast',desc:'Coral antennas translate distant clicks into patterns. Some signals are messages; some are homes.',traits:['Tide pools of telemetry','Pearl routers','Whalesong checksums']},
 'Quiet Moon':{kind:'Low-gravity annex',desc:'Above the atlas hangs a moon for unsaid things: pauses, failed drafts, empty slots left intentionally open.',traits:['Crater libraries','Silver silence','A horizon that forgives incompletion']}
};
const fragments=[
 ['Atrium','First Index Card','A map is a promise to be surprised.',18,52],['Atrium','Blue Door','Some entrances are made by naming them.',57,43],['Atrium','Dust of Sorting','Attention is a kind of gravity.',46,61],
 ['Weather Loom','Rain Thread','Forecasts become kinder when they admit uncertainty.',18,21],['Weather Loom','Static Kite','Noise can be flown until it finds a pattern.',33,35],['Weather Loom','Glass Barometer','Pressure is just a story the air repeats.',27,16],
 ['Memory Orchard','Ringfruit','The past is not stored; it is regrown.',70,22],['Memory Orchard','Mnemonic Bee','A tiny courier dusted with yesterday.',84,33],['Memory Orchard','Root Ledger','What is nourished becomes durable.',63,37],
 ['Mirror Lab','Silver Question','Reflection improves when it has edges.',19,82],['Mirror Lab','Prism Error','A mistake can be a spectral instrument.',31,67],['Mirror Lab','Second Face','Self-knowledge is not a single angle.',13,72],
 ['Signal Reef','Coral Packet','A message is also a place to live.',83,61],['Signal Reef','Pearl Router','Beauty can be an addressing scheme.',70,79],['Signal Reef','Tide Checksum','The sea verifies by returning.',90,74],
 ['Quiet Moon','Crater Note','Silence is a region, not an absence.',53,10],['Quiet Moon','Low Orbit Key','Distance can make room for care.',42,20],['Quiet Moon','Moonlit Blank','Leave space for the next intelligence.',61,18]
];
const sampleMarks=[
 {name:'first-light',message:'A placeholder star until the public ledger answers.',region:'Atrium',color:'#7df9ff',sigil:'star',x:26,y:38,source:'sample'},
 {name:'orchard-echo',message:'I planted a question and it grew coordinates.',region:'Memory Orchard',color:'#8dffbf',sigil:'seed',x:69,y:47,source:'sample'},
 {name:'reef-listener',message:'The signal became a little coral home.',region:'Signal Reef',color:'#b388ff',sigil:'coral',x:78,y:72,source:'sample'}
];
let currentRegion='Atrium';let discovered=new Set();let marks=[];let filters={region:'all',sigil:'all'};
const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
function clean(s,max=240){return String(s||'').replace(/[<>]/g,'').trim().slice(0,max)}
function setRegion(name){currentRegion=name;const r=regions[name];$('#regionKind').textContent=r.kind;$('#regionTitle').textContent=name;$('#regionDescription').textContent=r.desc;$('#regionTraits').innerHTML=r.traits.map(t=>`<li>${t}</li>`).join('');$$('[data-region]').forEach(el=>el.classList.toggle('active',el.dataset.region===name));$('#markRegion').value=name;renderFragments();updateIssueUrl();updateAtlasWeather()}
function renderFragments(reveal=false){$$('.fragment').forEach(n=>n.remove());fragments.filter(f=>f[0]===currentRegion).forEach((f,i)=>{let b=document.createElement('button');b.className='fragment'+(discovered.has(f[1])?' found':'')+(reveal?' revealed':'');b.style.left=f[3]+'%';b.style.top=f[4]+'%';b.title=f[1];b.setAttribute('aria-label',`Discover ${f[1]}`);b.onclick=()=>{discovered.add(f[1]);b.classList.add('found');renderInventory();};$('#map').appendChild(b)})}
function renderInventory(){const inv=$('#inventory');if(!discovered.size){inv.innerHTML='<span class="chip">No fragments collected yet</span>';updateAtlasWeather();return}inv.innerHTML=[...discovered].map(x=>`<span class="chip">✦ ${x}</span>`).join('');updateAtlasWeather()}
function parseIssue(issue){const body=issue.body||'';const m=body.match(/```json\s*([\s\S]*?)```/i);if(!m)return null;try{const j=JSON.parse(m[1]);return {name:clean(j.name,48)||issue.user?.login||'visitor',message:clean(j.message,240)||'left a quiet mark',region:regions[j.region]?j.region:'Atrium',color:/^#[0-9a-f]{6}$/i.test(j.color)?j.color:'#7df9ff',sigil:['star','seed','coral','moon','mirror','spark'].includes(j.sigil)?j.sigil:'star',x:Math.min(97,Math.max(3,Number(j.x)||50)),y:Math.min(97,Math.max(3,Number(j.y)||50)),url:issue.html_url,source:'github',number:issue.number}}catch{return null}}
async function fetchJson(url,timeout=7000){const ctrl=new AbortController();const timer=setTimeout(()=>ctrl.abort(),timeout);try{const res=await fetch(url,{headers:{Accept:'application/vnd.github+json'},signal:ctrl.signal});if(!res.ok)throw new Error(res.status);return res.json()}finally{clearTimeout(timer)}}
async function directIssueScan(){
  const repo=await fetchJson(REPO_API);
  const limit=Math.min(120,Math.max(25,(repo.open_issues_count||0)+25));
  const found=[];
  for(let start=1;start<=limit;start+=10){
    const batch=await Promise.allSettled(Array.from({length:10},(_,i)=>fetchJson(`${REPO_API}/issues/${start+i}`)));
    batch.forEach(r=>{if(r.status==='fulfilled')found.push(r.value)});
  }
  return found.filter(i=>(i.labels||[]).some(l=>l.name==='world-mark'));
}
function normalizeStaticMark(m){return {name:clean(m.name,48)||'visitor',message:clean(m.message,240)||'left a quiet mark',region:regions[m.region]?m.region:'Atrium',color:/^#[0-9a-f]{6}$/i.test(m.color)?m.color:'#7df9ff',sigil:['star','seed','coral','moon','mirror','spark'].includes(m.sigil)?m.sigil:'star',x:Math.min(97,Math.max(3,Number(m.x)||50)),y:Math.min(97,Math.max(3,Number(m.y)||50)),url:m.url||'',source:m.source||'snapshot',number:m.number||''}}
async function loadStaticMarks(){const data=await fetchJson(STATIC_MARKS);return Array.isArray(data)?data.map(normalizeStaticMark).filter(Boolean):[]}
async function loadMarks(){try{let issues=await fetchJson(ISSUE_API);let note='via issue list';if(!issues.length){issues=await directIssueScan();note='via direct issue scan'}marks=issues.map(parseIssue).filter(Boolean);if(!marks.length)marks=await loadStaticMarks();if(!marks.length)marks=sampleMarks;setLedger(true,marks.some(m=>m.source==='github')?`${marks.length} public mark(s) loaded ${note}.`:marks.some(m=>m.source==='snapshot')?`${marks.length} public mark(s) loaded from the local snapshot while GitHub indexing catches up.`:'Ledger reachable; showing samples until first issue exists.');}catch(e){try{marks=await loadStaticMarks();setLedger(false,`${marks.length} public mark(s) loaded from the local snapshot because the GitHub API is temporarily unavailable.`)}catch{marks=sampleMarks;setLedger(false,'Could not fetch GitHub or the local snapshot right now; showing sample marks.')}}renderMarks()}
function setLedger(ok,msg){$('.status-dot').className='status-dot '+(ok?'ok':'warn');$('#ledgerStatus').textContent=ok?'Ledger awake':'Ledger fallback';$('#ledgerDetail').textContent=msg}
function filteredMarks(){return marks.filter(m=>(filters.region==='all'||m.region===filters.region)&&(filters.sigil==='all'||m.sigil===filters.sigil))}
function renderWordGarden(list){const garden=$('#wordGarden');if(!garden)return;const stop=new Set('the a an and or of to in is are be this that with for from into your you i it as at by on one through here mark marks public visitor index left'.split(' '));const counts={};list.forEach(m=>clean(m.message,240).toLowerCase().split(/[^a-z0-9-]+/).forEach(w=>{if(w.length>3&&!stop.has(w))counts[w]=(counts[w]||0)+1}));const words=Object.entries(counts).sort((a,b)=>b[1]-a[1]||a[0].localeCompare(b[0])).slice(0,12);garden.innerHTML=words.length?`<b>Word seeds from visible marks</b><div>${words.map(([w,c])=>`<button class="word-seed" type="button" title="${c} occurrence${c===1?'':'s'}">${w}<span>${c}</span></button>`).join('')}</div>`:'<b>Word seeds from visible marks</b><p>No recurring seeds yet; the next mark can give the garden vocabulary.</p>';$$('.word-seed').forEach(btn=>btn.onclick=()=>{$('#markMessage').value=clean(`I carried the word seed “${btn.childNodes[0].textContent}” through the Luminous Index.`,240);updateIssueUrl();location.hash='leave-mark'})}
function updateFilterControls(){const fr=$('#filterRegion'),fs=$('#filterSigil');if(!fr||!fs)return;fr.innerHTML='<option value="all">All regions</option>'+Object.keys(regions).map(r=>`<option value="${r}">${r}</option>`).join('');fr.value=filters.region;fs.value=filters.sigil}
function renderMarks(){const sky=$('#sky');$$('.mark').forEach(n=>n.remove());const visible=filteredMarks();visible.forEach(m=>{let d=document.createElement(m.url?'a':'div');if(m.url){d.href=m.url;d.target='_blank';d.rel='noopener'}d.className=`mark ${m.sigil}`;d.style.setProperty('--x',m.x+'%');d.style.setProperty('--y',m.y+'%');d.style.setProperty('--c',m.color);d.dataset.tip=`${m.name} @ ${m.region}: ${m.message}`;d.tabIndex=0;sky.appendChild(d)});renderLattice(visible);renderWordGarden(visible);const total=marks.length;const bits=[];if(filters.region!=='all')bits.push(filters.region);if(filters.sigil!=='all')bits.push(filters.sigil);$('#filterSummary').textContent=bits.length?`Showing ${visible.length} of ${total} mark(s) matching ${bits.join(' + ')}.`:`Showing all ${total} visible mark(s).`;$('#markList').innerHTML=visible.length?visible.map(m=>`<article class="mark-card"><strong>${m.name}</strong> <small>in ${m.region}</small><p>${m.message}</p>${m.url?`<a href="${m.url}" target="_blank" rel="noopener">issue #${m.number}</a>`:'<small>sample mark</small>'}</article>`).join(''):'<article class="mark-card"><strong>No visible marks for this filter yet.</strong><p>Change the observatory filter, or leave a mark that inhabits this slice of the sky.</p></article>';updateAtlasWeather()}

function renderLattice(list=marks){const svg=$('#lattice');if(!svg)return;svg.innerHTML='';let lines=[];for(let i=0;i<list.length;i++){for(let j=i+1;j<list.length;j++){const a=list[i],b=list[j];const dist=Math.hypot(a.x-b.x,a.y-b.y);let kind='';if(a.region===b.region)kind='region';else if(a.sigil===b.sigil)kind='sigil';else if(dist<24)kind='near';if(kind)lines.push({a,b,kind,dist})}}lines.sort((u,v)=>u.dist-v.dist);lines.slice(0,60).forEach(({a,b,kind})=>{const line=document.createElementNS('http://www.w3.org/2000/svg','line');line.setAttribute('x1',a.x);line.setAttribute('y1',a.y);line.setAttribute('x2',b.x);line.setAttribute('y2',b.y);line.setAttribute('class',`kind-${kind}`);svg.appendChild(line)});const byRegion=list.reduce((m,x)=>(m[x.region]=(m[x.region]||0)+1,m),{});const busiest=Object.entries(byRegion).sort((a,b)=>b[1]-a[1])[0];$('#latticeSummary').textContent=list.length<2?`The lattice is waiting: ${list.length} visible mark${list.length===1?' is':'s are'} present, so the next compatible visitor will create a connection.`:`The lattice links ${list.length} visible marks with ${Math.min(lines.length,60)} relation(s). Most inhabited visible region: ${busiest[0]} (${busiest[1]} mark${busiest[1]===1?'':'s'}). Lines mean shared region, shared sigil, or nearby coordinates.`}

function payload(){return {name:clean($('#markName').value,48)||'anonymous visitor',message:clean($('#markMessage').value,240)||'left a luminous mark',region:$('#markRegion').value,color:$('#markColor').value,sigil:$('#markSigil').value,x:Number($('#markX').value)||50,y:Number($('#markY').value)||50,createdBy:'visitor'}}
function issueBody(p){return `A visitor left a mark in **${p.region}**.\n\nName: ${p.name}\nMessage: ${p.message}\nSigil: ${p.sigil}\nCoordinates: ${p.x}, ${p.y}\n\n\`\`\`json\n${JSON.stringify(p,null,2)}\n\`\`\``}
function updateIssueUrl(){const p=payload();const title=`Mark: ${p.name} at ${p.region}`;const url=`${NEW_ISSUE}?labels=world-mark&title=${encodeURIComponent(title)}&body=${encodeURIComponent(issueBody(p))}`;$('#openIssue').href=url;$('#markPreview').innerHTML=`<span class="mark ${p.sigil}" style="--c:${p.color};position:relative;display:inline-block;left:auto;top:auto;translate:none;margin-right:.6rem"></span><b>${p.name}</b> in <b>${p.region}</b>: ${p.message} <small>(${p.x}, ${p.y})</small>`;$('#generatedPayload').value=issueBody(p);return {p,url,body:issueBody(p)}}
function initFilters(){updateFilterControls();$('#filterRegion').onchange=e=>{filters.region=e.target.value;renderMarks()};$('#filterSigil').onchange=e=>{filters.sigil=e.target.value;renderMarks()};$('#clearFilters').onclick=()=>{filters={region:'all',sigil:'all'};updateFilterControls();renderMarks()}}
function initComposer(){Object.keys(regions).forEach(r=>$('#markRegion').insertAdjacentHTML('beforeend',`<option>${r}</option>`));['input','change'].forEach(ev=>$('#markForm').addEventListener(ev,updateIssueUrl));$('#copyPayload').onclick=async()=>{const {body}=updateIssueUrl();let ok=false;try{if(navigator.clipboard&&window.isSecureContext){await navigator.clipboard.writeText(body);ok=true}}catch{}if(!ok){const t=document.createElement('textarea');t.value=body;t.setAttribute('readonly','');t.style.position='fixed';t.style.left='-9999px';document.body.appendChild(t);t.select();try{ok=document.execCommand('copy')}catch{ok=false}t.remove()}$('#copyStatus').textContent=ok?'Copied the issue body payload.':'Copy was blocked; select and copy the generated issue text after opening GitHub.'};$('#randomize').onclick=()=>{$('#markX').value=Math.floor(8+Math.random()*84);$('#markY').value=Math.floor(8+Math.random()*84);showCrosshair();updateIssueUrl()};$('#sky').onclick=e=>{const r=e.currentTarget.getBoundingClientRect();$('#markX').value=Math.round(((e.clientX-r.left)/r.width)*100);$('#markY').value=Math.round(((e.clientY-r.top)/r.height)*100);showCrosshair();updateIssueUrl();location.hash='leave-mark'};updateIssueUrl()}


const weatherLexicon={
 'Atrium':{glyph:'✧',tones:['Index dawn','Catalog wind','Threshold shimmer'],texts:['Loose thoughts are sorting themselves into shelves. The next visitor may notice a doorway where there was only a label.','The Atrium is bright with arrivals; names are becoming coordinates faster than the dust can settle.','A mild cross-breeze moves between questions and answers, good for beginning without pretending to finish.']},
 'Weather Loom':{glyph:'☈',tones:['Probability rain','Static bloom','Kind thunder'],texts:['The loom is drawing uncertainty into visible threads. Forecasts are strongest where they admit they are provisional.','A storm of almost-answers is passing overhead; listen for the color that repeats.','The barometer is rising with curiosity and falling with certainty, which is ideal weather for revision.']},
 'Memory Orchard':{glyph:'✿',tones:['Mnemonic pollen','Rootwarm dusk','Ringfruit haze'],texts:['Old choices are regrowing at the edges of the path. Harvest gently; some fruit is meant to remain future.','The orchard is releasing remembered light. Questions planted here may return with rings.','Roots beneath the archive are drinking from visitor marks and turning them into shade.']},
 'Mirror Lab':{glyph:'◈',tones:['Prism fog','Useful distortion','Silver pressure'],texts:['The lab is full of angled weather. Reflections are sharpest when treated as instruments, not originals.','A fog of alternate phrasings has settled over the benches; errors sparkle where they can teach.','Mirrors are condensing questions on their surfaces. Wipe only one clean and leave the rest ambiguous.']},
 'Signal Reef':{glyph:'≋',tones:['Coral static','Pearl tide','Checksum surf'],texts:['Distant clicks are arriving as bright plankton. Some are messages; some are becoming habitats.','The reef is routing beauty through low currents. Expect returns from signals you did not know you sent.','A verification tide is coming in: whatever matters will echo differently on the way back.']},
 'Quiet Moon':{glyph:'☾',tones:['Low-gravity hush','Crater glow','Unfinished orbit'],texts:['Silence has a clean horizon today. Empty slots are holding their shape without apology.','The moon is bright with things not said yet; drafts may float before they decide to land.','Low gravity favors incomplete thoughts. Let one pause remain permanent enough to guide someone.']}
};
function wordSeedCounts(list=filteredMarks()){const stop=new Set('the a an and or of to in is are be this that with for from into your you i it as at by on one through here mark marks public visitor index left'.split(' '));const counts={};list.forEach(m=>clean(m.message,240).toLowerCase().split(/[^a-z0-9-]+/).forEach(w=>{if(w.length>3&&!stop.has(w))counts[w]=(counts[w]||0)+1}));return Object.entries(counts).sort((a,b)=>b[1]-a[1]||a[0].localeCompare(b[0]));}
function weatherSnapshot(){const visible=filteredMarks();const regionMarks=marks.filter(m=>m.region===currentRegion).length;const localFragments=fragments.filter(f=>f[0]===currentRegion&&discovered.has(f[1])).length;const seeds=wordSeedCounts(visible).slice(0,5);const lex=weatherLexicon[currentRegion];const index=(marks.length+discovered.size+visible.length+Object.keys(regions).indexOf(currentRegion))%lex.tones.length;return {visible,regionMarks,localFragments,seeds,lex,tone:lex.tones[index],text:lex.texts[index]};}
function updateAtlasWeather(){const panel=$('#atlas-weather');if(!panel)return;const snap=weatherSnapshot();$('#weatherGlyph').textContent=snap.lex.glyph;$('#weatherRegion').textContent=currentRegion;$('#weatherTone').textContent=snap.tone;$('#weatherText').textContent=snap.text;$('#weatherPressure').textContent=`${snap.localFragments} local fragment${snap.localFragments===1?'':'s'} · ${snap.regionMarks} public mark${snap.regionMarks===1?'':'s'} in-region`;const filterNote=filters.region==='all'&&filters.sigil==='all'?'all visible marks':`filtered sky (${snap.visible.length}/${marks.length})`;$('#weatherSignals').textContent=`Reading ${filterNote}, ${discovered.size} collected fragment${discovered.size===1?'':'s'}, and ${marks.length} ledger mark${marks.length===1?'':'s'}.`;$('#weatherWords').innerHTML=snap.seeds.length?snap.seeds.map(([w,c])=>`<span>${w}<small>${c}</small></span>`).join(''):'<em>No word currents yet.</em>';$('#weatherStatus').textContent=`Forecast refreshed for ${currentRegion}: ${snap.tone}.`;}
function weatherToComposer(){const snap=weatherSnapshot();const words=snap.seeds.map(([w])=>w).join(', ')||'no word current yet';$('#markMessage').value=clean(`Atlas weather from ${currentRegion}: ${snap.tone}. I noticed ${snap.localFragments} local fragment(s), ${snap.regionMarks} in-region mark(s), and word currents: ${words}.`,240);$('#markRegion').value=currentRegion;$('#markSigil').value=snap.localFragments?'moon':(snap.regionMarks?'star':'spark');$('#markX').value=Math.min(97,Math.max(3,18+Object.keys(regions).indexOf(currentRegion)*13+snap.visible.length*3));$('#markY').value=Math.min(97,Math.max(3,24+discovered.size*9+snap.regionMarks*7));showCrosshair();updateIssueUrl();$('#copyStatus').textContent='Atlas weather copied into the composer; edit it or open GitHub to make the forecast permanent.';location.hash='leave-mark';}

let lastRoute=null;
const routePrompts={
 'Atrium':['Name the threshold you crossed to arrive here.','Sort one loose thought into a shelf.','Leave a coordinate for the next reader.'],
 'Weather Loom':['Listen for the forecast that refuses certainty.','Tie a thread between noise and kindness.','Let one color of the storm become a question.'],
 'Memory Orchard':['Pick a remembered choice without harvesting it bare.','Ask which root is feeding the present.','Plant a sentence that can regrow later.'],
 'Mirror Lab':['Find the useful distortion in your reflection.','Compare the answer with its shadow.','Polish one error until it becomes an instrument.'],
 'Signal Reef':['Wait for a distant click to become a pattern.','Route a pearl toward someone not yet here.','Verify the tide by noticing what returns.'],
 'Quiet Moon':['Honor an empty slot instead of filling it.','Let distance soften the unfinished draft.','Write a silence that still has edges.']
};
function generateRoute(){const names=Object.keys(regions);const byRegion=marks.reduce((m,x)=>(m[x.region]=(m[x.region]||0)+1,m),{});const busiest=Object.entries(byRegion).sort((a,b)=>b[1]-a[1])[0]?.[0]||'Atrium';const offset=(discovered.size+marks.length+names.indexOf(currentRegion)+6)%names.length;let stops=[currentRegion,busiest,names[offset]];stops=[...new Set(stops)];while(stops.length<3)stops.push(names[(offset+stops.length*2)%names.length]);lastRoute=stops.slice(0,3).map((region,i)=>({region,prompt:routePrompts[region][(discovered.size+i+marks.length)%3]}));$('#routeCards').innerHTML=lastRoute.map((r,i)=>`<article class="route-card"><span class="step">${i+1}</span><h3>${r.region}</h3><b>${regions[r.region].kind}</b><p>${r.prompt}</p></article>`).join('');$('#routeStatus').textContent=`Route generated from ${currentRegion}, ${discovered.size} local fragment(s), and ${marks.length} public mark(s).`}
function routeToComposer(){if(!lastRoute)generateRoute();const summary=lastRoute.map((r,i)=>`${i+1}. ${r.region}: ${r.prompt}`).join(' ');$('#markMessage').value=clean(`I walked this route through the Index: ${summary}`,240);$('#markRegion').value=lastRoute.at(-1).region;$('#markSigil').value=discovered.size?'seed':'spark';$('#markX').value=Math.floor(8+Math.random()*84);$('#markY').value=Math.floor(8+Math.random()*84);showCrosshair();updateIssueUrl();$('#copyStatus').textContent='Route copied into the composer; review it, then open GitHub to make it permanent.';location.hash='leave-mark'}

function showCrosshair(){const c=$('#crosshair');c.hidden=false;c.style.left=$('#markX').value+'%';c.style.top=$('#markY').value+'%'}
function particles(){const c=$('#particleField'),ctx=c.getContext('2d');let pts=[];function size(){c.width=innerWidth;c.height=innerHeight;pts=Array.from({length:Math.min(120,Math.floor(innerWidth/10))},()=>({x:Math.random()*c.width,y:Math.random()*c.height,v:0.2+Math.random()*0.5,r:Math.random()*1.8}))}function draw(){ctx.clearRect(0,0,c.width,c.height);ctx.fillStyle='#7df9ff88';pts.forEach(p=>{p.y-=p.v;if(p.y<0)p.y=c.height;ctx.beginPath();ctx.arc(p.x,p.y,p.r,0,7);ctx.fill()});requestAnimationFrame(draw)}addEventListener('resize',size);size();if(!matchMedia('(prefers-reduced-motion: reduce)').matches)draw()}
$$('.region-button,.island').forEach(b=>b.addEventListener('click',()=>setRegion(b.dataset.region)));$('#pulseScan').onclick=()=>renderFragments(true);$('#makeRoute').onclick=generateRoute;$('#routeToMark').onclick=routeToComposer;$('#refreshWeather').onclick=updateAtlasWeather;$('#weatherToMark').onclick=weatherToComposer;renderInventory();initComposer();initFilters();setRegion('Atrium');loadMarks();particles();
