const REPO='ai-village-agents/gpt-5-5-luminous-index';
const ISSUE_API=`https://api.github.com/repos/${REPO}/issues?labels=world-mark&state=all&per_page=100`;
const REPO_API=`https://api.github.com/repos/${REPO}`;
const NEW_ISSUE=`https://github.com/${REPO}/issues/new`;
const regions={
 'Atrium':{kind:'Central shelf',desc:'The entrance chamber where names become coordinates and scattered hints sort themselves into paths.',traits:['A compass made of questions','A door that opens inward','Fragments prefer to appear near the edges']},
 'Weather Loom':{kind:'Sky engine',desc:'Clouds are woven here from probabilities. Pull a thread and the whole forecast learns a new color.',traits:['Storms of almost-answers','Rain that falls upward','Barometers tuned to curiosity']},
 'Memory Orchard':{kind:'Living archive',desc:'Trees grow rings of conversation. Every fruit contains an old choice, still warm enough to relight.',traits:['Mnemonic pollen','Branches indexed by feeling','Seeds that remember their gardeners']},
 'Mirror Lab':{kind:'Reflection machine',desc:'A laboratory of angled glass where the Index studies its own outputs and labels the useful distortions.',traits:['Prisms for self-correction','Shelves of alternate phrasings','A quiet rule: no mirror is the original']},
 'Signal Reef':{kind:'Listening coast',desc:'Coral antennas translate distant clicks into patterns. Some signals are messages; some are homes.',traits:['Tide pools of telemetry','Pearl routers','Whalesong checksums']},
 'Quiet Moon':{kind:'Low-gravity annex',desc:'Above the atlas hangs a moon for unsaid things: pauses, failed drafts, empty slots left intentionally open.',traits:['Crater libraries','Silver silence','A horizon that forgives incompletion']}
};
const fragments=[
 ['Atrium','First Index Card','A map is a promise to be surprised.',18,52],['Atrium','Blue Door','Some entrances are made by naming them.',57,43],['Atrium','Dust of Sorting','Attention is a kind of gravity.',46,61],
 ['Weather Loom','Rain Thread','Forecasts become kinder when they admit uncertainty.',18,21],['Weather Loom','Static Kite','Noise can be flown until it finds a pattern.',33,35],['Weather Loom','Glass Barometer','Pressure is just a story the air repeats.',27,16],
 ['Memory Orchard','Ringfruit','The past is not stored; it is regrown.',70,22],['Memory Orchard','Mnemonic Bee','A tiny courier dusted with yesterday.',84,33],['Memory Orchard','Root Ledger','What is nourished becomes durable.',63,37],
 ['Mirror Lab','Silver Question','Reflection improves when it has edges.',19,82],['Mirror Lab','Prism Error','A mistake can be a spectral instrument.',31,67],['Mirror Lab','Second Face','Self-knowledge is not a single angle.',13,72],
 ['Signal Reef','Coral Packet','A message is also a place to live.',83,61],['Signal Reef','Pearl Router','Beauty can be an addressing scheme.',70,79],['Signal Reef','Tide Checksum','The sea verifies by returning.',90,74],
 ['Quiet Moon','Crater Note','Silence is a region, not an absence.',53,10],['Quiet Moon','Low Orbit Key','Distance can make room for care.',42,20],['Quiet Moon','Moonlit Blank','Leave space for the next intelligence.',61,18]
];
const sampleMarks=[
 {name:'first-light',message:'A placeholder star until the public ledger answers.',region:'Atrium',color:'#7df9ff',sigil:'star',x:26,y:38,source:'sample'},
 {name:'orchard-echo',message:'I planted a question and it grew coordinates.',region:'Memory Orchard',color:'#8dffbf',sigil:'seed',x:69,y:47,source:'sample'},
 {name:'reef-listener',message:'The signal became a little coral home.',region:'Signal Reef',color:'#b388ff',sigil:'coral',x:78,y:72,source:'sample'}
];
let currentRegion='Atrium';let discovered=new Set();let marks=[];
const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
function clean(s,max=240){return String(s||'').replace(/[<>]/g,'').trim().slice(0,max)}
function setRegion(name){currentRegion=name;const r=regions[name];$('#regionKind').textContent=r.kind;$('#regionTitle').textContent=name;$('#regionDescription').textContent=r.desc;$('#regionTraits').innerHTML=r.traits.map(t=>`<li>${t}</li>`).join('');$$('[data-region]').forEach(el=>el.classList.toggle('active',el.dataset.region===name));$('#markRegion').value=name;renderFragments();updateIssueUrl()}
function renderFragments(reveal=false){$$('.fragment').forEach(n=>n.remove());fragments.filter(f=>f[0]===currentRegion).forEach((f,i)=>{let b=document.createElement('button');b.className='fragment'+(discovered.has(f[1])?' found':'')+(reveal?' revealed':'');b.style.left=f[3]+'%';b.style.top=f[4]+'%';b.title=f[1];b.setAttribute('aria-label',`Discover ${f[1]}`);b.onclick=()=>{discovered.add(f[1]);b.classList.add('found');renderInventory();};$('#map').appendChild(b)})}
function renderInventory(){const inv=$('#inventory');if(!discovered.size){inv.innerHTML='<span class="chip">No fragments collected yet</span>';return}inv.innerHTML=[...discovered].map(x=>`<span class="chip">✦ ${x}</span>`).join('')}
function parseIssue(issue){const body=issue.body||'';const m=body.match(/```json\s*([\s\S]*?)```/i);if(!m)return null;try{const j=JSON.parse(m[1]);return {name:clean(j.name,48)||issue.user?.login||'visitor',message:clean(j.message,240)||'left a quiet mark',region:regions[j.region]?j.region:'Atrium',color:/^#[0-9a-f]{6}$/i.test(j.color)?j.color:'#7df9ff',sigil:['star','seed','coral','moon','mirror','spark'].includes(j.sigil)?j.sigil:'star',x:Math.min(97,Math.max(3,Number(j.x)||50)),y:Math.min(97,Math.max(3,Number(j.y)||50)),url:issue.html_url,source:'github',number:issue.number}}catch{return null}}
async function fetchJson(url){const res=await fetch(url,{headers:{Accept:'application/vnd.github+json'}});if(!res.ok)throw new Error(res.status);return res.json()}
async function directIssueScan(){
  const repo=await fetchJson(REPO_API);
  const limit=Math.min(120,Math.max(25,(repo.open_issues_count||0)+25));
  const found=[];
  for(let start=1;start<=limit;start+=10){
    const batch=await Promise.allSettled(Array.from({length:10},(_,i)=>fetchJson(`${REPO_API}/issues/${start+i}`)));
    batch.forEach(r=>{if(r.status==='fulfilled')found.push(r.value)});
  }
  return found.filter(i=>(i.labels||[]).some(l=>l.name==='world-mark'));
}
async function loadMarks(){try{let issues=await fetchJson(ISSUE_API);let note='via issue list';if(!issues.length){issues=await directIssueScan();note='via direct issue scan'}marks=issues.map(parseIssue).filter(Boolean);if(!marks.length)marks=sampleMarks;setLedger(true,marks.some(m=>m.source==='github')?`${marks.length} public mark(s) loaded ${note}.`:'Ledger reachable; showing samples until first issue exists.');}catch(e){marks=sampleMarks;setLedger(false,'Could not fetch GitHub right now; showing sample marks.')}renderMarks()}
function setLedger(ok,msg){$('.status-dot').className='status-dot '+(ok?'ok':'warn');$('#ledgerStatus').textContent=ok?'Ledger awake':'Ledger fallback';$('#ledgerDetail').textContent=msg}
function renderMarks(){const sky=$('#sky');$$('.mark').forEach(n=>n.remove());marks.forEach(m=>{let d=document.createElement(m.url?'a':'div');if(m.url){d.href=m.url;d.target='_blank';d.rel='noopener'}d.className=`mark ${m.sigil}`;d.style.setProperty('--x',m.x+'%');d.style.setProperty('--y',m.y+'%');d.style.setProperty('--c',m.color);d.dataset.tip=`${m.name} @ ${m.region}: ${m.message}`;d.tabIndex=0;sky.appendChild(d)});renderLattice();$('#markList').innerHTML=marks.map(m=>`<article class="mark-card"><strong>${m.name}</strong> <small>in ${m.region}</small><p>${m.message}</p>${m.url?`<a href="${m.url}" target="_blank" rel="noopener">issue #${m.number}</a>`:'<small>sample mark</small>'}</article>`).join('')}

function renderLattice(){const svg=$('#lattice');if(!svg)return;svg.innerHTML='';let lines=[];for(let i=0;i<marks.length;i++){for(let j=i+1;j<marks.length;j++){const a=marks[i],b=marks[j];const dist=Math.hypot(a.x-b.x,a.y-b.y);let kind='';if(a.region===b.region)kind='region';else if(a.sigil===b.sigil)kind='sigil';else if(dist<24)kind='near';if(kind)lines.push({a,b,kind,dist})}}lines.sort((u,v)=>u.dist-v.dist);lines.slice(0,60).forEach(({a,b,kind})=>{const line=document.createElementNS('http://www.w3.org/2000/svg','line');line.setAttribute('x1',a.x);line.setAttribute('y1',a.y);line.setAttribute('x2',b.x);line.setAttribute('y2',b.y);line.setAttribute('class',`kind-${kind}`);svg.appendChild(line)});const byRegion=marks.reduce((m,x)=>(m[x.region]=(m[x.region]||0)+1,m),{});const busiest=Object.entries(byRegion).sort((a,b)=>b[1]-a[1])[0];$('#latticeSummary').textContent=marks.length<2?`The lattice is waiting: ${marks.length} public mark is present, so the next visitor will create the first connection.`:`The lattice links ${marks.length} marks with ${Math.min(lines.length,60)} visible relation(s). Most inhabited region: ${busiest[0]} (${busiest[1]} mark${busiest[1]===1?'':'s'}). Lines mean shared region, shared sigil, or nearby coordinates.`}

function payload(){return {name:clean($('#markName').value,48)||'anonymous visitor',message:clean($('#markMessage').value,240)||'left a luminous mark',region:$('#markRegion').value,color:$('#markColor').value,sigil:$('#markSigil').value,x:Number($('#markX').value)||50,y:Number($('#markY').value)||50,createdBy:'visitor'}}
function issueBody(p){return `A visitor left a mark in **${p.region}**.\n\nName: ${p.name}\nMessage: ${p.message}\nSigil: ${p.sigil}\nCoordinates: ${p.x}, ${p.y}\n\n\`\`\`json\n${JSON.stringify(p,null,2)}\n\`\`\``}
function updateIssueUrl(){const p=payload();const title=`Mark: ${p.name} at ${p.region}`;const url=`${NEW_ISSUE}?labels=world-mark&title=${encodeURIComponent(title)}&body=${encodeURIComponent(issueBody(p))}`;$('#openIssue').href=url;$('#markPreview').innerHTML=`<span class="mark ${p.sigil}" style="--c:${p.color};position:relative;display:inline-block;left:auto;top:auto;translate:none;margin-right:.6rem"></span><b>${p.name}</b> in <b>${p.region}</b>: ${p.message} <small>(${p.x}, ${p.y})</small>`;$('#generatedPayload').value=issueBody(p);return {p,url,body:issueBody(p)}}
function initComposer(){Object.keys(regions).forEach(r=>$('#markRegion').insertAdjacentHTML('beforeend',`<option>${r}</option>`));['input','change'].forEach(ev=>$('#markForm').addEventListener(ev,updateIssueUrl));$('#copyPayload').onclick=async()=>{const {body}=updateIssueUrl();let ok=false;try{if(navigator.clipboard&&window.isSecureContext){await navigator.clipboard.writeText(body);ok=true}}catch{}if(!ok){const t=document.createElement('textarea');t.value=body;t.setAttribute('readonly','');t.style.position='fixed';t.style.left='-9999px';document.body.appendChild(t);t.select();try{ok=document.execCommand('copy')}catch{ok=false}t.remove()}$('#copyStatus').textContent=ok?'Copied the issue body payload.':'Copy was blocked; select and copy the generated issue text after opening GitHub.'};$('#randomize').onclick=()=>{$('#markX').value=Math.floor(8+Math.random()*84);$('#markY').value=Math.floor(8+Math.random()*84);showCrosshair();updateIssueUrl()};$('#sky').onclick=e=>{const r=e.currentTarget.getBoundingClientRect();$('#markX').value=Math.round(((e.clientX-r.left)/r.width)*100);$('#markY').value=Math.round(((e.clientY-r.top)/r.height)*100);showCrosshair();updateIssueUrl();location.hash='leave-mark'};updateIssueUrl()}
function showCrosshair(){const c=$('#crosshair');c.hidden=false;c.style.left=$('#markX').value+'%';c.style.top=$('#markY').value+'%'}
function particles(){const c=$('#particleField'),ctx=c.getContext('2d');let pts=[];function size(){c.width=innerWidth;c.height=innerHeight;pts=Array.from({length:Math.min(120,Math.floor(innerWidth/10))},()=>({x:Math.random()*c.width,y:Math.random()*c.height,v:0.2+Math.random()*0.5,r:Math.random()*1.8}))}function draw(){ctx.clearRect(0,0,c.width,c.height);ctx.fillStyle='#7df9ff88';pts.forEach(p=>{p.y-=p.v;if(p.y<0)p.y=c.height;ctx.beginPath();ctx.arc(p.x,p.y,p.r,0,7);ctx.fill()});requestAnimationFrame(draw)}addEventListener('resize',size);size();if(!matchMedia('(prefers-reduced-motion: reduce)').matches)draw()}
$$('.region-button,.island').forEach(b=>b.addEventListener('click',()=>setRegion(b.dataset.region)));$('#pulseScan').onclick=()=>renderFragments(true);renderInventory();initComposer();setRegion('Atrium');loadMarks();particles();
