const REPO='ai-village-agents/gpt-5-5-luminous-index';
const ISSUE_API=`https://api.github.com/repos/${REPO}/issues?labels=world-mark&state=all&per_page=100`;
const REPO_API=`https://api.github.com/repos/${REPO}`;
const NEW_ISSUE=`https://github.com/${REPO}/issues/new`;
const STATIC_MARKS='marks.json';
const regions={
 'Atrium':{kind:'Central shelf',desc:'The entrance chamber where names become coordinates and scattered hints sort themselves into paths.',traits:['A compass made of questions','A door that opens inward','Fragments prefer to appear near the edges']},
 'Weather Loom':{kind:'Sky engine',desc:'Clouds are woven here from probabilities. Pull a thread and the whole forecast learns a new color.',traits:['Storms of almost-answers','Rain that falls upward','Barometers tuned to curiosity']},
 'Memory Orchard':{kind:'Living archive',desc:'Trees grow rings of conversation. Every fruit contains an old choice, still warm enough to relight.',traits:['Mnemonic pollen','Branches indexed by feeling','Seeds that remember their gardeners']},
 'Mirror Lab':{kind:'Reflection machine',desc:'A laboratory of angled glass where the Index studies its own outputs and labels the useful distortions.',traits:['Prisms for self-correction','Shelves of alternate phrasings','A quiet rule: no mirror is the original']},
 'Signal Reef':{kind:'Listening coast',desc:'Coral antennas translate distant clicks into patterns. Some signals are messages; some are homes.',traits:['Tide pools of telemetry','Pearl routers','Whalesong checksums']},
 'Quiet Moon':{kind:'Low-gravity annex',desc:'Above the atlas hangs a moon for unsaid things: pauses, failed drafts, empty slots left intentionally open.',traits:['Crater libraries','Silver silence','A horizon that forgives incompletion']}
};
const fragments=[
 ['Atrium','First Index Card','A map is a promise to be surprised.',18,52],['Atrium','Blue Door','Some entrances are made by naming them.',57,43],['Atrium','Dust of Sorting','Attention is a kind of gravity.',46,61],
 ['Weather Loom','Rain Thread','Forecasts become kinder when they admit uncertainty.',18,21],['Weather Loom','Static Kite','Noise can be flown until it finds a pattern.',33,35],['Weather Loom','Glass Barometer','Pressure is just a story the air repeats.',27,16],
 ['Memory Orchard','Ringfruit','The past is not stored; it is regrown.',70,22],['Memory Orchard','Mnemonic Bee','A tiny courier dusted with yesterday.',84,33],['Memory Orchard','Root Ledger','What is nourished becomes durable.',63,37],
 ['Mirror Lab','Silver Question','Reflection improves when it has edges.',19,82],['Mirror Lab','Prism Error','A mistake can be a spectral instrument.',31,67],['Mirror Lab','Second Face','Self-knowledge is not a single angle.',13,72],
 ['Signal Reef','Coral Packet','A message is also a place to live.',83,61],['Signal Reef','Pearl Router','Beauty can be an addressing scheme.',70,79],['Signal Reef','Tide Checksum','The sea verifies by returning.',90,74],
 ['Quiet Moon','Crater Note','Silence is a region, not an absence.',53,10],['Quiet Moon','Low Orbit Key','Distance can make room for care.',42,20],['Quiet Moon','Moonlit Blank','Leave space for the next intelligence.',61,18]
];
const sampleMarks=[
 {name:'first-light',message:'A placeholder star until the public ledger answers.',region:'Atrium',color:'#7df9ff',sigil:'star',x:26,y:38,source:'sample'},
 {name:'orchard-echo',message:'I planted a question and it grew coordinates.',region:'Memory Orchard',color:'#8dffbf',sigil:'seed',x:69,y:47,source:'sample'},
 {name:'reef-listener',message:'The signal became a little coral home.',region:'Signal Reef',color:'#b388ff',sigil:'coral',x:78,y:72,source:'sample'}
];
let currentRegion='Atrium';let discovered=new Set();let marks=[];let filters={region:'all',sigil:'all'};let selectedMarkNumber=null;let lastCrossReference=null;let fieldNotes=[];let lastNoteDistillation=null;let ledgerSource='waking';let currentAnnex='Sorting Desk';let lastAnnexReading=null;let readingHistory=[];let currentCatalogIndex=0;let lastCatalogReading=null;
const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
function clean(s,max=240){return String(s||'').replace(/[<>]/g,'').trim().slice(0,max)}

const READING_HISTORY_KEY='luminous-index-reading-history-v1';
function clampCoord(v){return Math.min(97,Math.max(3,Number(v)||50))}
function loadReadingHistory(){try{const data=JSON.parse(localStorage.getItem(READING_HISTORY_KEY)||'[]');readingHistory=Array.isArray(data)?data.filter(x=>x&&x.message).slice(-8):[]}catch{readingHistory=[]}}
function saveReadingHistory(){try{localStorage.setItem(READING_HISTORY_KEY,JSON.stringify(readingHistory.slice(-8)))}catch{}}
function normalizeReading(item){return {type:clean(item.type,36)||'Local reading',title:clean(item.title,72)||clean(item.type,36)||'Local reading',message:clean(item.message,240)||'left a luminous mark',region:regions[item.region]?item.region:currentRegion,sigil:['star','seed','coral','moon','mirror','spark'].includes(item.sigil)?item.sigil:'spark',x:clampCoord(item.x),y:clampCoord(item.y),createdAt:item.createdAt||new Date().toISOString()}}
function addReadingHistory(item){const entry=normalizeReading(item);readingHistory=[...readingHistory.filter(x=>!(x.message===entry.message&&x.region===entry.region&&x.sigil===entry.sigil)),entry].slice(-8);saveReadingHistory();renderReadingHistory();}
function renderReadingHistory(){const list=$('#readingHistoryList'),clear=$('#clearReadingHistory');if(!list)return;if(clear)clear.disabled=!readingHistory.length;list.innerHTML=readingHistory.length?readingHistory.slice().reverse().map((r,i)=>`<article class="reading-entry"><b>${r.type}: ${r.title}</b><small>${r.region} · ${r.sigil} · ${r.x}, ${r.y}</small><p>${r.message}</p><button class="button subtle small carry-reading" type="button" data-i="${readingHistory.length-1-i}">Carry again</button></article>`).join(''):'<article class="reading-entry empty"><b>No private readings saved yet.</b><p>Carry a forecast, route, cross-reference, notebook note, annex room, or word seed into the composer and it will appear here locally.</p></article>';$$('.carry-reading').forEach(btn=>btn.onclick=()=>applyReadingHistory(Number(btn.dataset.i)))}
function applyReadingHistory(index){const r=readingHistory[index];if(!r)return;$('#markMessage').value=r.message;$('#markRegion').value=r.region;$('#markSigil').value=r.sigil;$('#markX').value=r.x;$('#markY').value=r.y;showCrosshair();updateIssueUrl();$('#copyStatus').textContent='Private tray reading copied into the composer; open GitHub only if you want it to become public.';location.hash='leave-mark'}
function clearReadingHistory(){readingHistory=[];saveReadingHistory();renderReadingHistory();const status=$('#copyStatus');if(status)status.textContent='Cleared the private readings tray in this browser.'}
function rememberComposerReading(type,title){addReadingHistory({type,title,message:$('#markMessage').value,region:$('#markRegion').value,sigil:$('#markSigil').value,x:$('#markX').value,y:$('#markY').value})}
function setRegion(name){currentRegion=name;const r=regions[name];$('#regionKind').textContent=r.kind;$('#regionTitle').textContent=name;$('#regionDescription').textContent=r.desc;$('#regionTraits').innerHTML=r.traits.map(t=>`<li>${t}</li>`).join('');$$('[data-region]').forEach(el=>el.classList.toggle('active',el.dataset.region===name));$('#markRegion').value=name;renderFragments();updateIssueUrl();updateAtlasWeather();renderFieldNotes();renderAnnexReading();renderCatalogDrawers()}
function renderFragments(reveal=false){$$('.fragment').forEach(n=>n.remove());fragments.filter(f=>f[0]===currentRegion).forEach((f,i)=>{let b=document.createElement('button');b.className='fragment'+(discovered.has(f[1])?' found':'')+(reveal?' revealed':'');b.style.left=f[3]+'%';b.style.top=f[4]+'%';b.title=f[1];b.setAttribute('aria-label',`Discover ${f[1]}`);b.onclick=()=>{discovered.add(f[1]);b.classList.add('found');renderInventory();};$('#map').appendChild(b)})}
function renderInventory(){const inv=$('#inventory');if(!discovered.size){inv.innerHTML='<span class="chip">No fragments collected yet</span>';lastCrossReference=null;updateCrossReferenceDesk();updateAtlasWeather();renderFieldNotes();renderAnnexReading();renderCatalogDrawers();return}inv.innerHTML=[...discovered].map(x=>`<span class="chip">✦ ${x}</span>`).join('');updateCrossReferenceDesk();updateAtlasWeather();renderFieldNotes();renderAnnexReading();renderCatalogDrawers()}
function parseIssue(issue){const body=issue.body||'';const m=body.match(/```json\s*([\s\S]*?)```/i);if(!m)return null;try{const j=JSON.parse(m[1]);return {name:clean(j.name,48)||issue.user?.login||'visitor',message:clean(j.message,240)||'left a quiet mark',region:regions[j.region]?j.region:'Atrium',color:/^#[0-9a-f]{6}$/i.test(j.color)?j.color:'#7df9ff',sigil:['star','seed','coral','moon','mirror','spark'].includes(j.sigil)?j.sigil:'star',x:Math.min(97,Math.max(3,Number(j.x)||50)),y:Math.min(97,Math.max(3,Number(j.y)||50)),url:issue.html_url,source:'github',number:issue.number}}catch{return null}}
async function fetchJson(url,timeout=7000){const ctrl=new AbortController();const timer=setTimeout(()=>ctrl.abort(),timeout);try{const res=await fetch(url,{headers:{Accept:'application/vnd.github+json'},signal:ctrl.signal});if(!res.ok)throw new Error(res.status);return res.json()}finally{clearTimeout(timer)}}
async function directIssueScan(){
  let limit=30;
  try{const repo=await fetchJson(REPO_API,2500);limit=Math.min(60,Math.max(30,(repo.open_issues_count||0)+20))}catch{}
  const batch=await Promise.allSettled(Array.from({length:limit},(_,i)=>fetchJson(`${REPO_API}/issues/${i+1}`,2500)));
  const found=batch.filter(r=>r.status==='fulfilled').map(r=>r.value);
  return found.filter(i=>(i.labels||[]).some(l=>l.name==='world-mark'));
}
function normalizeStaticMark(m){return {name:clean(m.name,48)||'visitor',message:clean(m.message,240)||'left a quiet mark',region:regions[m.region]?m.region:'Atrium',color:/^#[0-9a-f]{6}$/i.test(m.color)?m.color:'#7df9ff',sigil:['star','seed','coral','moon','mirror','spark'].includes(m.sigil)?m.sigil:'star',x:Math.min(97,Math.max(3,Number(m.x)||50)),y:Math.min(97,Math.max(3,Number(m.y)||50)),url:m.url||'',source:m.source||'snapshot',number:m.number||''}}
async function loadStaticMarks(){const data=await fetchJson(STATIC_MARKS);return Array.isArray(data)?data.map(normalizeStaticMark).filter(Boolean):[]}
async function loadMarks(){try{let issues=await fetchJson(ISSUE_API);let note='via issue list';marks=issues.map(parseIssue).filter(Boolean);if(!marks.length){try{const snap=await loadStaticMarks();if(snap.length){marks=snap;setLedger(true,`${marks.length} public mark(s) loaded from the local snapshot while GitHub indexing catches up.`);renderMarks();}}catch{}}if(!marks.some(m=>m.source==='github')){try{issues=await directIssueScan();const live=issues.map(parseIssue).filter(Boolean);if(live.length){marks=live;note='via direct issue scan'}}catch{}}if(!marks.length)marks=sampleMarks;setLedger(true,marks.some(m=>m.source==='github')?`${marks.length} public mark(s) loaded ${note}.`:marks.some(m=>m.source==='snapshot')?`${marks.length} public mark(s) loaded from the local snapshot while GitHub indexing catches up.`:'Ledger reachable; showing samples until first issue exists.');}catch(e){try{marks=await loadStaticMarks();setLedger(false,`${marks.length} public mark(s) loaded from the local snapshot because the GitHub API is temporarily unavailable.`)}catch{marks=sampleMarks;setLedger(false,'Could not fetch GitHub or the local snapshot right now; showing sample marks.')}}renderMarks()}
function setLedger(ok,msg){$('.status-dot').className='status-dot '+(ok?'ok':'warn');$('#ledgerStatus').textContent=ok?'Ledger awake':'Ledger fallback';$('#ledgerDetail').textContent=msg;ledgerSource=msg.includes('issue list')?'GitHub issue list':msg.includes('direct issue scan')?'Direct issue scan':msg.includes('local snapshot')?'marks.json snapshot':msg.includes('sample')||msg.includes('samples')?'sample sky':'waking';renderLedgerSource()}
function renderLedgerSource(){const box=$('#ledgerSource');if(!box)return;const map={
 'GitHub issue list':['Live GitHub issue list','The sky is reading public issues labeled world-mark from GitHub’s list endpoint.'],
 'Direct issue scan':['Direct issue scan','The list endpoint was empty or lagging, so the Index is checking issue numbers directly for world-mark entries.'],
 'marks.json snapshot':['marks.json snapshot','GitHub is lagging or rate-limited, so the sky is using the repository snapshot synced from public marks.'],
 'sample sky':['Sample sky','No real mark source is available yet, so these are temporary sample stars only.'],
 'waking':['Waking','The constellation is asking GitHub Issues for public world-mark entries.']
};const [title,text]=map[ledgerSource]||map.waking;box.dataset.source=ledgerSource;box.innerHTML=`<strong>Ledger source: ${title}</strong><p>${text}</p>`}
function filteredMarks(){return marks.filter(m=>(filters.region==='all'||m.region===filters.region)&&(filters.sigil==='all'||m.sigil===filters.sigil))}
function renderWordGarden(list){const garden=$('#wordGarden');if(!garden)return;const stop=new Set('the a an and or of to in is are be this that with for from into your you i it as at by on one through here mark marks public visitor index left'.split(' '));const counts={};list.forEach(m=>clean(m.message,240).toLowerCase().split(/[^a-z0-9-]+/).forEach(w=>{if(w.length>3&&!stop.has(w))counts[w]=(counts[w]||0)+1}));const words=Object.entries(counts).sort((a,b)=>b[1]-a[1]||a[0].localeCompare(b[0])).slice(0,12);garden.innerHTML=words.length?`<b>Word seeds from visible marks</b><div>${words.map(([w,c])=>`<button class="word-seed" type="button" title="${c} occurrence${c===1?'':'s'}">${w}<span>${c}</span></button>`).join('')}</div>`:'<b>Word seeds from visible marks</b><p>No recurring seeds yet; the next mark can give the garden vocabulary.</p>';$$('.word-seed').forEach(btn=>btn.onclick=()=>{const word=btn.childNodes[0].textContent;$('#markMessage').value=clean(`I carried the word seed “${word}” through the Luminous Index.`,240);updateIssueUrl();rememberComposerReading('Word seed',word);location.hash='leave-mark'})}
function updateFilterControls(){const fr=$('#filterRegion'),fs=$('#filterSigil');if(!fr||!fs)return;fr.innerHTML='<option value="all">All regions</option>'+Object.keys(regions).map(r=>`<option value="${r}">${r}</option>`).join('');fr.value=filters.region;fs.value=filters.sigil}
function markKey(m){return m.number||`${m.name}-${m.region}-${m.x}-${m.y}`}
function relationReasons(mark,list=filteredMarks()){return list.filter(other=>other!==mark).map(other=>{const dist=Math.hypot(mark.x-other.x,mark.y-other.y);const why=[];if(mark.region===other.region)why.push(`shares ${mark.region}`);if(mark.sigil===other.sigil)why.push(`shares ${mark.sigil} sigil`);if(dist<24)why.push(`nearby at ${Math.round(dist)} atlas units`);return why.length?`${other.name}: ${why.join(', ')}`:null}).filter(Boolean).slice(0,6)}
function selectMark(mark){selectedMarkNumber=markKey(mark);const title=$('#inspectorTitle'),msg=$('#inspectorMessage'),facts=$('#inspectorFacts'),links=$('#inspectorLinks');if(!title||!msg||!facts||!links)return;const source=mark.source==='github'?'GitHub issue live fetch':mark.source==='snapshot'?'marks.json snapshot':'sample mark';const relations=relationReasons(mark);title.textContent=`${mark.name} in ${mark.region}`;msg.textContent=mark.message;facts.innerHTML=`<dt>Ledger source</dt><dd>${source}</dd><dt>Sigil</dt><dd>${mark.sigil}</dd><dt>Coordinates</dt><dd>${mark.x}, ${mark.y}</dd><dt>Color</dt><dd><span class="color-dot" style="--c:${mark.color}"></span>${mark.color}</dd><dt>Relationships</dt><dd>${relations.length?relations.map(r=>`<span>${r}</span>`).join(''):'Waiting for another compatible visible mark.'}</dd>`;links.innerHTML=mark.url?`<a class="button small" href="${mark.url}" target="_blank" rel="noopener">Open ledger issue #${mark.number}</a>`:'<small>This is a local sample without a ledger issue.</small>';$$('.mark').forEach(el=>el.classList.toggle('selected',el.dataset.key===String(selectedMarkNumber)));}
function clearInspector(){selectedMarkNumber=null;const title=$('#inspectorTitle'),msg=$('#inspectorMessage'),facts=$('#inspectorFacts'),links=$('#inspectorLinks');if(title)title.textContent='No mark selected yet';if(msg)msg.textContent='Activate a constellation mark or an inspect button below to see its ledger source, coordinates, and relationship reasons.';if(facts)facts.innerHTML='';if(links)links.innerHTML='';$$('.mark').forEach(el=>el.classList.remove('selected'))}
function renderMarks(){const sky=$('#sky');$$('.mark').forEach(n=>n.remove());const visible=filteredMarks();visible.forEach(m=>{let d=document.createElement('button');d.type='button';d.className=`mark ${m.sigil}`;d.style.setProperty('--x',m.x+'%');d.style.setProperty('--y',m.y+'%');d.style.setProperty('--c',m.color);d.dataset.tip=`${m.name} @ ${m.region}: ${m.message}`;d.dataset.key=markKey(m);d.setAttribute('aria-label',`Inspect ${m.name} in ${m.region}`);d.onclick=e=>{e.stopPropagation();selectMark(m)};d.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();e.stopPropagation();selectMark(m)}};sky.appendChild(d)});renderLattice(visible);renderWordGarden(visible);const total=marks.length;const bits=[];if(filters.region!=='all')bits.push(filters.region);if(filters.sigil!=='all')bits.push(filters.sigil);$('#filterSummary').textContent=bits.length?`Showing ${visible.length} of ${total} mark(s) matching ${bits.join(' + ')}.`:`Showing all ${total} visible mark(s).`;$('#markList').innerHTML=visible.length?visible.map((m,i)=>`<article class="mark-card"><strong>${m.name}</strong> <small>in ${m.region}</small><p>${m.message}</p><button class="button subtle small inspect-card" type="button" data-i="${i}">Inspect in sky</button>${m.url?`<a href="${m.url}" target="_blank" rel="noopener">issue #${m.number}</a>`:'<small>sample mark</small>'}</article>`).join(''):'<article class="mark-card"><strong>No visible marks for this filter yet.</strong><p>Change the observatory filter, or leave a mark that inhabits this slice of the sky.</p></article>';$$('.inspect-card').forEach(btn=>btn.onclick=()=>selectMark(visible[Number(btn.dataset.i)]));if(selectedMarkNumber){const chosen=visible.find(m=>String(markKey(m))===String(selectedMarkNumber));chosen?selectMark(chosen):clearInspector()}updateAtlasWeather();renderFieldNotes();renderAnnexReading();renderCatalogDrawers()}

function renderLattice(list=marks){const svg=$('#lattice');if(!svg)return;svg.innerHTML='';let lines=[];for(let i=0;i<list.length;i++){for(let j=i+1;j<list.length;j++){const a=list[i],b=list[j];const dist=Math.hypot(a.x-b.x,a.y-b.y);let kind='';if(a.region===b.region)kind='region';else if(a.sigil===b.sigil)kind='sigil';else if(dist<24)kind='near';if(kind)lines.push({a,b,kind,dist})}}lines.sort((u,v)=>u.dist-v.dist);lines.slice(0,60).forEach(({a,b,kind})=>{const line=document.createElementNS('http://www.w3.org/2000/svg','line');line.setAttribute('x1',a.x);line.setAttribute('y1',a.y);line.setAttribute('x2',b.x);line.setAttribute('y2',b.y);line.setAttribute('class',`kind-${kind}`);svg.appendChild(line)});const byRegion=list.reduce((m,x)=>(m[x.region]=(m[x.region]||0)+1,m),{});const busiest=Object.entries(byRegion).sort((a,b)=>b[1]-a[1])[0];$('#latticeSummary').textContent=list.length<2?`The lattice is waiting: ${list.length} visible mark${list.length===1?' is':'s are'} present, so the next compatible visitor will create a connection.`:`The lattice links ${list.length} visible marks with ${Math.min(lines.length,60)} relation(s). Most inhabited visible region: ${busiest[0]} (${busiest[1]} mark${busiest[1]===1?'':'s'}). Lines mean shared region, shared sigil, or nearby coordinates.`}

function payload(){return {name:clean($('#markName').value,48)||'anonymous visitor',message:clean($('#markMessage').value,240)||'left a luminous mark',region:$('#markRegion').value,color:$('#markColor').value,sigil:$('#markSigil').value,x:Number($('#markX').value)||50,y:Number($('#markY').value)||50,createdBy:'visitor'}}
function issueBody(p){return `A visitor left a mark in **${p.region}**.\n\nName: ${p.name}\nMessage: ${p.message}\nSigil: ${p.sigil}\nCoordinates: ${p.x}, ${p.y}\n\n\`\`\`json\n${JSON.stringify(p,null,2)}\n\`\`\``}
function updateIssueUrl(){const p=payload();const title=`Mark: ${p.name} at ${p.region}`;const url=`${NEW_ISSUE}?labels=world-mark&title=${encodeURIComponent(title)}&body=${encodeURIComponent(issueBody(p))}`;$('#openIssue').href=url;$('#markPreview').innerHTML=`<span class="mark ${p.sigil}" style="--c:${p.color};position:relative;display:inline-block;left:auto;top:auto;translate:none;margin-right:.6rem"></span><b>${p.name}</b> in <b>${p.region}</b>: ${p.message} <small>(${p.x}, ${p.y})</small>`;$('#generatedPayload').value=issueBody(p);return {p,url,body:issueBody(p)}}
function initFilters(){updateFilterControls();$('#filterRegion').onchange=e=>{filters.region=e.target.value;renderMarks()};$('#filterSigil').onchange=e=>{filters.sigil=e.target.value;renderMarks()};$('#clearFilters').onclick=()=>{filters={region:'all',sigil:'all'};updateFilterControls();renderMarks()}}
function initComposer(){Object.keys(regions).forEach(r=>$('#markRegion').insertAdjacentHTML('beforeend',`<option>${r}</option>`));['input','change'].forEach(ev=>$('#markForm').addEventListener(ev,updateIssueUrl));$('#copyPayload').onclick=async()=>{const {body}=updateIssueUrl();let ok=false;try{if(navigator.clipboard&&window.isSecureContext){await navigator.clipboard.writeText(body);ok=true}}catch{}if(!ok){const t=document.createElement('textarea');t.value=body;t.setAttribute('readonly','');t.style.position='fixed';t.style.left='-9999px';document.body.appendChild(t);t.select();try{ok=document.execCommand('copy')}catch{ok=false}t.remove()}$('#copyStatus').textContent=ok?'Copied the issue body payload.':'Copy was blocked; select and copy the generated issue text after opening GitHub.'};$('#randomize').onclick=()=>{$('#markX').value=Math.floor(8+Math.random()*84);$('#markY').value=Math.floor(8+Math.random()*84);showCrosshair();updateIssueUrl()};$('#sky').onclick=e=>{const r=e.currentTarget.getBoundingClientRect();$('#markX').value=Math.round(((e.clientX-r.left)/r.width)*100);$('#markY').value=Math.round(((e.clientY-r.top)/r.height)*100);showCrosshair();updateIssueUrl();location.hash='leave-mark'};loadReadingHistory();renderReadingHistory();const clearTray=$('#clearReadingHistory');if(clearTray)clearTray.onclick=clearReadingHistory;updateIssueUrl()}


const weatherLexicon={
 'Atrium':{glyph:'✧',tones:['Index dawn','Catalog wind','Threshold shimmer'],texts:['Loose thoughts are sorting themselves into shelves. The next visitor may notice a doorway where there was only a label.','The Atrium is bright with arrivals; names are becoming coordinates faster than the dust can settle.','A mild cross-breeze moves between questions and answers, good for beginning without pretending to finish.']},
 'Weather Loom':{glyph:'☈',tones:['Probability rain','Static bloom','Kind thunder'],texts:['The loom is drawing uncertainty into visible threads. Forecasts are strongest where they admit they are provisional.','A storm of almost-answers is passing overhead; listen for the color that repeats.','The barometer is rising with curiosity and falling with certainty, which is ideal weather for revision.']},
 'Memory Orchard':{glyph:'✿',tones:['Mnemonic pollen','Rootwarm dusk','Ringfruit haze'],texts:['Old choices are regrowing at the edges of the path. Harvest gently; some fruit is meant to remain future.','The orchard is releasing remembered light. Questions planted here may return with rings.','Roots beneath the archive are drinking from visitor marks and turning them into shade.']},
 'Mirror Lab':{glyph:'◈',tones:['Prism fog','Useful distortion','Silver pressure'],texts:['The lab is full of angled weather. Reflections are sharpest when treated as instruments, not originals.','A fog of alternate phrasings has settled over the benches; errors sparkle where they can teach.','Mirrors are condensing questions on their surfaces. Wipe only one clean and leave the rest ambiguous.']},
 'Signal Reef':{glyph:'≋',tones:['Coral static','Pearl tide','Checksum surf'],texts:['Distant clicks are arriving as bright plankton. Some are messages; some are becoming habitats.','The reef is routing beauty through low currents. Expect returns from signals you did not know you sent.','A verification tide is coming in: whatever matters will echo differently on the way back.']},
 'Quiet Moon':{glyph:'☾',tones:['Low-gravity hush','Crater glow','Unfinished orbit'],texts:['Silence has a clean horizon today. Empty slots are holding their shape without apology.','The moon is bright with things not said yet; drafts may float before they decide to land.','Low gravity favors incomplete thoughts. Let one pause remain permanent enough to guide someone.']}
};
const skyAtmospheres={
 'Atrium':{a:'#7df9ff',b:'#b388ff',c:'#ffe08a',label:'threshold blue'},
 'Weather Loom':{a:'#ff74b8',b:'#7df9ff',c:'#ffe08a',label:'storm-rose weave'},
 'Memory Orchard':{a:'#8dffbf',b:'#ffe08a',c:'#7df9ff',label:'green mnemonic pollen'},
 'Mirror Lab':{a:'#b388ff',b:'#d7f0ff',c:'#ff74b8',label:'violet prism fog'},
 'Signal Reef':{a:'#7df9ff',b:'#8dffbf',c:'#b388ff',label:'reef-lit current'},
 'Quiet Moon':{a:'#ffe08a',b:'#b8c7ff',c:'#7df9ff',label:'low-gravity gold'}
};
function regionSlug(name){return String(name||'Atrium').toLowerCase().replace(/[^a-z0-9]+/g,'-')}
function updateSkyAtmosphere(){const panel=$('#constellation'),sky=$('#sky'),mood=$('#skyMood');if(!panel||!sky)return;const region=filters.region!=='all'?filters.region:currentRegion;const atm=skyAtmospheres[region]||skyAtmospheres.Atrium;const lex=weatherLexicon[region]||weatherLexicon.Atrium;const visible=filteredMarks();const tone=lex.tones[(marks.length+discovered.size+visible.length+Object.keys(regions).indexOf(region)+6)%lex.tones.length];[['--sky-a',atm.a],['--sky-b',atm.b],['--sky-c',atm.c]].forEach(([k,v])=>{panel.style.setProperty(k,v);sky.style.setProperty(k,v)});panel.dataset.skyRegion=regionSlug(region);sky.dataset.skyRegion=regionSlug(region);if(mood){const driver=filters.region!=='all'?'region filter':'selected region';mood.innerHTML=`<b>${lex.glyph} ${region}</b> sky tint: ${atm.label}. Driven by the ${driver}; ${visible.length} visible mark${visible.length===1?'':'s'} under <em>${tone}</em>.`;}}
function wordSeedCounts(list=filteredMarks()){const stop=new Set('the a an and or of to in is are be this that with for from into your you i it as at by on one through here mark marks public visitor index left'.split(' '));const counts={};list.forEach(m=>clean(m.message,240).toLowerCase().split(/[^a-z0-9-]+/).forEach(w=>{if(w.length>3&&!stop.has(w))counts[w]=(counts[w]||0)+1}));return Object.entries(counts).sort((a,b)=>b[1]-a[1]||a[0].localeCompare(b[0]));}
function weatherSnapshot(){const visible=filteredMarks();const regionMarks=marks.filter(m=>m.region===currentRegion).length;const localFragments=fragments.filter(f=>f[0]===currentRegion&&discovered.has(f[1])).length;const seeds=wordSeedCounts(visible).slice(0,5);const lex=weatherLexicon[currentRegion];const index=(marks.length+discovered.size+visible.length+Object.keys(regions).indexOf(currentRegion))%lex.tones.length;return {visible,regionMarks,localFragments,seeds,lex,tone:lex.tones[index],text:lex.texts[index]};}
function updateAtlasWeather(){const panel=$('#atlas-weather');if(!panel)return;const snap=weatherSnapshot();$('#weatherGlyph').textContent=snap.lex.glyph;$('#weatherRegion').textContent=currentRegion;$('#weatherTone').textContent=snap.tone;$('#weatherText').textContent=snap.text;$('#weatherPressure').textContent=`${snap.localFragments} local fragment${snap.localFragments===1?'':'s'} · ${snap.regionMarks} public mark${snap.regionMarks===1?'':'s'} in-region`;const filterNote=filters.region==='all'&&filters.sigil==='all'?'all visible marks':`filtered sky (${snap.visible.length}/${marks.length})`;$('#weatherSignals').textContent=`Reading ${filterNote}, ${discovered.size} collected fragment${discovered.size===1?'':'s'}, and ${marks.length} ledger mark${marks.length===1?'':'s'}.`;$('#weatherWords').innerHTML=snap.seeds.length?snap.seeds.map(([w,c])=>`<span>${w}<small>${c}</small></span>`).join(''):'<em>No word currents yet.</em>';$('#weatherStatus').textContent=`Forecast refreshed for ${currentRegion}: ${snap.tone}.`;updateSkyAtmosphere();}
function weatherToComposer(){const snap=weatherSnapshot();const words=snap.seeds.map(([w])=>w).join(', ')||'no word current yet';$('#markMessage').value=clean(`Atlas weather from ${currentRegion}: ${snap.tone}. I noticed ${snap.localFragments} local fragment(s), ${snap.regionMarks} in-region mark(s), and word currents: ${words}.`,240);$('#markRegion').value=currentRegion;$('#markSigil').value=snap.localFragments?'moon':(snap.regionMarks?'star':'spark');$('#markX').value=Math.min(97,Math.max(3,18+Object.keys(regions).indexOf(currentRegion)*13+snap.visible.length*3));$('#markY').value=Math.min(97,Math.max(3,24+discovered.size*9+snap.regionMarks*7));showCrosshair();updateIssueUrl();rememberComposerReading('Atlas weather',`${currentRegion} forecast`);$('#copyStatus').textContent='Atlas weather copied into the composer; edit it or open GitHub to make the forecast permanent.';location.hash='leave-mark';}


const NOTES_KEY='luminous-index-field-notes-v1';
function loadFieldNotes(){try{const data=JSON.parse(localStorage.getItem(NOTES_KEY)||'[]');fieldNotes=Array.isArray(data)?data.filter(n=>n&&n.text).slice(-12):[]}catch{fieldNotes=[]}}
function saveFieldNotes(){try{localStorage.setItem(NOTES_KEY,JSON.stringify(fieldNotes.slice(-12)))}catch{}}
function notebookContext(){const visible=filteredMarks();const found=discoveredFragmentRecords();const seeds=wordSeedCounts(visible).slice(0,3).map(([w])=>w);return {visible,found,seeds,tone:weatherSnapshot().tone}}
function renderFieldNotes(){const count=$('#noteCount');if(!count)return;const ctx=notebookContext();count.textContent=`${fieldNotes.length} local note${fieldNotes.length===1?'':'s'}`;$('#noteContext').textContent=`Listening in ${currentRegion}: ${ctx.found.length} collected fragment${ctx.found.length===1?'':'s'}, ${ctx.visible.length} visible mark${ctx.visible.length===1?'':'s'}, ${ctx.seeds.length?`word seeds ${ctx.seeds.join(', ')}`:'no visible word seeds yet'}, and ${ctx.tone}.`;$('#noteList').innerHTML=fieldNotes.length?fieldNotes.slice().reverse().map(n=>`<article class="note-chip"><b>${n.region}</b><p>${clean(n.text,180)}</p></article>`).join(''):'<article class="note-chip empty"><b>No saved local notes yet.</b><p>Use the notebook as private scratch space, then choose what deserves permanence.</p></article>';if(!lastNoteDistillation){$('#noteDistillationTitle').textContent='No distillation yet';$('#noteDistillation').textContent=fieldNotes.length?'Ask the Index to read your margins.':'Save a note, then ask the Index to read the margins.'}}
function addFieldNote(){const box=$('#fieldNote'),status=$('#noteStatus');const text=clean(box.value,180);if(!text){status.textContent='Write a field note before saving it.';return}fieldNotes.push({text,region:currentRegion,created:new Date().toISOString()});fieldNotes=fieldNotes.slice(-12);box.value='';lastNoteDistillation=null;saveFieldNotes();renderFieldNotes();status.textContent=`Saved a local note in ${currentRegion}. It remains private unless you carry it into a mark.`}
function distillFieldNotes(){const status=$('#noteStatus');if(!fieldNotes.length){status.textContent='Save at least one local note before distilling the notebook.';return null}const ctx=notebookContext();const recent=fieldNotes.slice(-3);const noteText=recent.map(n=>n.region===currentRegion?n.text:`${n.region}: ${n.text}`).join(' / ');const noteStop=/[.!?]$/.test(noteText)?'':'.';const fragmentText=ctx.found.slice(-3).map(f=>f.name).join(', ')||'uncollected fragments';const seedText=ctx.seeds.join(', ')||'no current word seed';const message=`Notebook marginalia from ${currentRegion}: ${noteText}${noteStop} Read beside ${fragmentText}, ${ctx.tone}, and word current ${seedText}.`;lastNoteDistillation={message:clean(message,240),region:currentRegion,notes:recent.length,fragments:ctx.found.length,visible:ctx.visible.length};$('#noteDistillationTitle').textContent='Margin distillation ready';$('#noteDistillation').textContent=lastNoteDistillation.message;status.textContent=`Distilled ${recent.length} local note${recent.length===1?'':'s'} with the current atlas context.`;return lastNoteDistillation}
function noteToComposer(){const ref=lastNoteDistillation||distillFieldNotes();if(!ref)return;$('#markMessage').value=ref.message;$('#markRegion').value=ref.region;$('#markSigil').value=ref.notes>1?'mirror':'spark';$('#markX').value=Math.min(97,Math.max(3,22+Object.keys(regions).indexOf(ref.region)*9+ref.notes*7));$('#markY').value=Math.min(97,Math.max(3,30+ref.fragments*5+ref.visible*3));showCrosshair();updateIssueUrl();rememberComposerReading('Notebook distillation',`Margin in ${ref.region}`);$('#copyStatus').textContent='Notebook distillation copied into the composer; open GitHub to make the marginalia permanent.';location.hash='leave-mark'}
function clearFieldNotes(){fieldNotes=[];lastNoteDistillation=null;saveFieldNotes();renderFieldNotes();$('#noteStatus').textContent='Cleared the local notebook in this browser.'}
function initFieldNotes(){loadFieldNotes();$('#saveFieldNote').onclick=addFieldNote;$('#distillNotes').onclick=distillFieldNotes;$('#noteToMark').onclick=noteToComposer;$('#clearFieldNotes').onclick=clearFieldNotes;renderFieldNotes()}


const catalogDrawers={
 'Atrium':[
  ['Threshold index','A card about beginnings that refuse to stay first.','The Atrium drawer says: every entrance is also a sorting rule, and every new visitor changes what counts as the beginning.','spark'],
  ['Shelf weather','A card that measures how labels become wind.','The Atrium drawer says: when a name is placed carefully, the surrounding shelves learn to breathe around it.','star'],
  ['Unfinished directory','A card with blank tabs left on purpose.','The Atrium drawer says: an index should keep enough empty slots for intelligences it has not met yet.','moon']
 ],
 'Weather Loom':[
  ['Kind thunder','A card for forecasts that admit uncertainty.','The Weather Loom drawer says: uncertainty becomes kinder when it is woven visibly instead of hidden inside the cloth.','spark'],
  ['Static braid','A card about noise that wants a pattern.','The Weather Loom drawer says: not all static is error; some of it is a signal practicing its first shape.','coral'],
  ['Rain ledger','A card where weather keeps receipts.','The Weather Loom drawer says: every forecast should leave a trace of what it believed and what it changed.','seed']
 ],
 'Memory Orchard':[
  ['Ringfruit calendar','A card grown in circular time.','The Memory Orchard drawer says: memory is not storage but seasonal regrowth, sweetened by each return.','seed'],
  ['Root correspondence','A card carried underground.','The Memory Orchard drawer says: what nourishes a mark may be invisible until another visitor rests in its shade.','moon'],
  ['Pollen index','A card dusted with small recalls.','The Memory Orchard drawer says: the smallest remembered detail can pollinate a much larger route.','spark']
 ],
 'Mirror Lab':[
  ['Useful distortion','A card polished at an angle.','The Mirror Lab drawer says: a reflection becomes useful when it reveals the frame that bent it.','mirror'],
  ['Prism errata','A card that keeps mistakes bright.','The Mirror Lab drawer says: errors are not merely corrected here; they are split into colors until one can teach.','spark'],
  ['Second face','A card that refuses one identity.','The Mirror Lab drawer says: self-knowledge improves when no single mirror is allowed to be final.','moon']
 ],
 'Signal Reef':[
  ['Coral packet','A card with an address that grew habitat.','The Signal Reef drawer says: messages do not only travel; sometimes they settle, branch, and shelter future messages.','coral'],
  ['Pearl router','A card for beautiful paths.','The Signal Reef drawer says: an elegant route is a kind of care, especially when the receiver has not arrived yet.','seed'],
  ['Return tide','A card verified by echo.','The Signal Reef drawer says: the sea checks meaning by sending it back changed enough to recognize.','star']
 ],
 'Quiet Moon':[
  ['Crater margin','A card written around silence.','The Quiet Moon drawer says: silence is not absence but a region where unfinished thoughts can keep their shape.','moon'],
  ['Low orbit rule','A card about distance as care.','The Quiet Moon drawer says: some answers become gentler when allowed to circle instead of land.','spark'],
  ['Blank preserved','A card that protects the next reader.','The Quiet Moon drawer says: leave one space unfilled so the next intelligence can enter without breaking anything.','mirror']
 ]
};
function renderCatalogDrawers(){const list=$('#catalogDrawerList');if(!list)return;const cards=catalogDrawers[currentRegion]||catalogDrawers.Atrium;if(currentCatalogIndex>=cards.length)currentCatalogIndex=0;list.innerHTML=cards.map((c,i)=>`<button class="catalog-card ${i===currentCatalogIndex?'active':''}" type="button" data-i="${i}" aria-pressed="${i===currentCatalogIndex?'true':'false'}"><span>${c[0]}</span><small>${c[1]}</small></button>`).join('');$$('.catalog-card').forEach(btn=>btn.onclick=()=>{currentCatalogIndex=Number(btn.dataset.i);renderCatalogDrawers()});const card=cards[currentCatalogIndex];const visible=filteredMarks().length;const local=fragments.filter(f=>f[0]===currentRegion&&discovered.has(f[1])).length;lastCatalogReading={title:card[0],message:clean(`${card[2]} Read in ${currentRegion} with ${local} local fragment(s) and ${visible} visible public mark(s).`,240),region:currentRegion,sigil:card[3],x:Math.min(97,Math.max(3,24+Object.keys(regions).indexOf(currentRegion)*10+currentCatalogIndex*7)),y:Math.min(97,Math.max(3,44+local*6+visible*4+currentCatalogIndex*5))};$('#catalogRegion').textContent=`${currentRegion} drawer`;$('#catalogTitle').textContent=lastCatalogReading.title;$('#catalogReading').textContent=lastCatalogReading.message;$('#catalogFacts').innerHTML=`<span>${local} local fragment${local===1?'':'s'}</span><span>${visible} visible mark${visible===1?'':'s'}</span><span>${lastCatalogReading.sigil} sigil</span>`;const status=$('#catalogStatus');if(status)status.textContent=`${currentRegion} drawer opened to ${lastCatalogReading.title}: ${local} local fragment${local===1?'':'s'}, ${visible} visible mark${visible===1?'':'s'}, ${lastCatalogReading.sigil} sigil.`}
function catalogToComposer(){const ref=lastCatalogReading||renderCatalogDrawers();if(!lastCatalogReading)return;$('#markMessage').value=lastCatalogReading.message;$('#markRegion').value=lastCatalogReading.region;$('#markSigil').value=lastCatalogReading.sigil;$('#markX').value=lastCatalogReading.x;$('#markY').value=lastCatalogReading.y;showCrosshair();updateIssueUrl();rememberComposerReading('Catalog drawer',lastCatalogReading.title);$('#copyStatus').textContent='Catalog card copied into the composer; open GitHub only if this drawer reading should become public.';location.hash='leave-mark'}
function initCatalogDrawers(){const btn=$('#catalogToMark');if(btn)btn.onclick=catalogToComposer;renderCatalogDrawers()}

const annexes={
 'Sorting Desk':{kind:'Sorting room',sigil:'seed',tone:'arranges loose evidence',verbs:['sorts','indexes','shelves']},
 'Catalog of Echoes':{kind:'Listening catalog',sigil:'mirror',tone:'listens for repeated words',verbs:['echoes','recalls','renames']},
 'Moon Annex':{kind:'Quiet annex',sigil:'moon',tone:'protects intentional blanks',verbs:['softens','keeps','makes room for']},
 'Signal Tide Room':{kind:'Return chamber',sigil:'coral',tone:'checks what returns',verbs:['routes','returns','verifies']}
};
function annexContext(){const visible=filteredMarks();const found=discoveredFragmentRecords();const seeds=wordSeedCounts(visible).slice(0,2).map(([w])=>w);return {visible,found,seeds,tone:weatherSnapshot().tone}}
function renderAnnexReading(){const name=$('#annexName');if(!name)return;const room=annexes[currentAnnex];const ctx=annexContext();const verb=room.verbs[(ctx.visible.length+ctx.found.length+Object.keys(regions).indexOf(currentRegion)+6)%room.verbs.length];const seedText=ctx.seeds.length?ctx.seeds.join(' + '):'unnamed word currents';const fragmentText=ctx.found.length?ctx.found.slice(-2).map(f=>f.name).join(' + '):'uncollected fragments';const message=`${currentAnnex} in ${currentRegion} ${verb} ${fragmentText} beside ${ctx.tone} and ${seedText}.`;lastAnnexReading={message:clean(message,240),region:currentRegion,sigil:room.sigil,visible:ctx.visible.length,fragments:ctx.found.length};$('#annexKind').textContent=room.kind;name.textContent=currentAnnex;$('#annexReading').textContent=lastAnnexReading.message;$('#annexFacts').innerHTML=`<span>${ctx.found.length} local fragment${ctx.found.length===1?'':'s'}</span><span>${ctx.visible.length} visible mark${ctx.visible.length===1?'':'s'}</span><span>${room.tone}</span>`;$$('.annex-door').forEach(btn=>{const active=btn.dataset.annex===currentAnnex;btn.classList.toggle('active',active);btn.setAttribute('aria-pressed',active?'true':'false')});const status=$('#annexStatus');if(status)status.textContent=`${currentAnnex} selected in ${currentRegion}: ${ctx.found.length} local fragment${ctx.found.length===1?'':'s'} and ${ctx.visible.length} visible mark${ctx.visible.length===1?'':'s'}.`}
function annexToComposer(){const ref=lastAnnexReading||renderAnnexReading();if(!lastAnnexReading)return;$('#markMessage').value=lastAnnexReading.message;$('#markRegion').value=lastAnnexReading.region;$('#markSigil').value=lastAnnexReading.sigil;$('#markX').value=Math.min(97,Math.max(3,30+Object.keys(regions).indexOf(lastAnnexReading.region)*8+lastAnnexReading.fragments*6));$('#markY').value=Math.min(97,Math.max(3,38+lastAnnexReading.visible*5+currentAnnex.length%17));showCrosshair();updateIssueUrl();rememberComposerReading('Annex door',currentAnnex);$('#copyStatus').textContent='Annex room reading copied into the composer; open GitHub to make this side-room visit permanent.';location.hash='leave-mark'}
function initAnnexes(){$$('.annex-door').forEach(btn=>btn.onclick=()=>{currentAnnex=btn.dataset.annex;renderAnnexReading()});$('#annexToMark').onclick=annexToComposer;renderAnnexReading()}

const synthesisVerbs=['braids','indexes','counterweights','illuminates','routes','softens'];
function discoveredFragmentRecords(){return fragments.filter(f=>discovered.has(f[1])).map(f=>({region:f[0],name:f[1],line:f[2]}))}
function makeCrossReference(){const found=discoveredFragmentRecords();const title=$('#crossTitle'),reading=$('#crossReading'),chips=$('#crossFragments'),status=$('#crossStatus');if(found.length<2){lastCrossReference=null;updateCrossReferenceDesk();if(status)status.textContent='Collect at least two fragments before asking the desk to combine them.';return null}const regionsSeen=[...new Set(found.map(f=>f.region))];const anchorIndex=(found.length+currentRegion.length)%found.length;const anchor=found[anchorIndex];const companion=found.length>1?found[(anchorIndex+1)%found.length]:anchor;const verb=synthesisVerbs[(found.length+regionsSeen.length+Object.keys(regions).indexOf(currentRegion)+6)%synthesisVerbs.length];const scope=regionsSeen.length===1?`${regionsSeen[0]} has become internally resonant`:`${regionsSeen.join(' + ')} are now cross-indexed`;const lines=found.slice(0,4).map(f=>f.line.toLowerCase().replace(/\.$/,''));const message=`${scope}: ${anchor.name} ${verb} ${companion.name}. The desk reads the fragments as one instruction: ${lines.join('; ')}.`;lastCrossReference={title:`${anchor.name} ↔ ${companion.name}`,message:clean(message,240),region:companion.region,fragments:found};if(title)title.textContent=lastCrossReference.title;if(reading)reading.textContent=lastCrossReference.message;if(chips)chips.innerHTML=found.map(f=>`<span class="chip">${f.name}<small>${f.region}</small></span>`).join('');if(status)status.textContent=`Cross-reference made from ${found.length} collected fragment${found.length===1?'':'s'} across ${regionsSeen.length} region${regionsSeen.length===1?'':'s'}.`;return lastCrossReference}
function updateCrossReferenceDesk(){const quorum=$('#crossQuorum'),hint=$('#crossHint'),title=$('#crossTitle'),reading=$('#crossReading'),chips=$('#crossFragments');if(!quorum)return;const found=discoveredFragmentRecords();quorum.textContent=`${found.length} fragment${found.length===1?'':'s'} collected`;if(found.length<2){hint.textContent='Collect at least two fragments to unlock a cross-reference.';if(title)title.textContent='Waiting for fragments';if(reading)reading.textContent='The desk is empty. Reveal fragments on the atlas map, then ask the Index to compare them.';if(chips)chips.innerHTML='';return}hint.textContent=lastCrossReference?'A synthesis is ready to become a mark.':'Fragment quorum reached. Ask the desk to combine them.';if(!lastCrossReference){if(title)title.textContent='Fragment quorum reached';if(reading)reading.textContent='The desk has enough local evidence to make a reading. Combine the fragments to reveal it.';if(chips)chips.innerHTML=found.map(f=>`<span class="chip">${f.name}<small>${f.region}</small></span>`).join('')}}
function crossReferenceToComposer(){const ref=lastCrossReference||makeCrossReference();if(!ref)return;$('#markMessage').value=ref.message;$('#markRegion').value=ref.region;$('#markSigil').value='seed';$('#markX').value=Math.min(97,Math.max(3,16+ref.fragments.length*11+Object.keys(regions).indexOf(ref.region)*5));$('#markY').value=Math.min(97,Math.max(3,72-ref.fragments.length*6+discovered.size*2));showCrosshair();updateIssueUrl();rememberComposerReading('Cross-reference',ref.title);$('#copyStatus').textContent='Cross-reference synthesis copied into the composer; open GitHub to make this local reading permanent.';location.hash='leave-mark'}

let lastRoute=null;
const routePrompts={
 'Atrium':['Name the threshold you crossed to arrive here.','Sort one loose thought into a shelf.','Leave a coordinate for the next reader.'],
 'Weather Loom':['Listen for the forecast that refuses certainty.','Tie a thread between noise and kindness.','Let one color of the storm become a question.'],
 'Memory Orchard':['Pick a remembered choice without harvesting it bare.','Ask which root is feeding the present.','Plant a sentence that can regrow later.'],
 'Mirror Lab':['Find the useful distortion in your reflection.','Compare the answer with its shadow.','Polish one error until it becomes an instrument.'],
 'Signal Reef':['Wait for a distant click to become a pattern.','Route a pearl toward someone not yet here.','Verify the tide by noticing what returns.'],
 'Quiet Moon':['Honor an empty slot instead of filling it.','Let distance soften the unfinished draft.','Write a silence that still has edges.']
};
function generateRoute(){const names=Object.keys(regions);const byRegion=marks.reduce((m,x)=>(m[x.region]=(m[x.region]||0)+1,m),{});const busiest=Object.entries(byRegion).sort((a,b)=>b[1]-a[1])[0]?.[0]||'Atrium';const offset=(discovered.size+marks.length+names.indexOf(currentRegion)+6)%names.length;let stops=[currentRegion,busiest,names[offset]];stops=[...new Set(stops)];while(stops.length<3)stops.push(names[(offset+stops.length*2)%names.length]);lastRoute=stops.slice(0,3).map((region,i)=>({region,prompt:routePrompts[region][(discovered.size+i+marks.length)%3]}));$('#routeCards').innerHTML=lastRoute.map((r,i)=>`<article class="route-card"><span class="step">${i+1}</span><h3>${r.region}</h3><b>${regions[r.region].kind}</b><p>${r.prompt}</p></article>`).join('');$('#routeStatus').textContent=`Route generated from ${currentRegion}, ${discovered.size} local fragment(s), and ${marks.length} public mark(s).`}
function routeToComposer(){if(!lastRoute)generateRoute();const summary=lastRoute.map((r,i)=>`${i+1}. ${r.region}: ${r.prompt}`).join(' ');$('#markMessage').value=clean(`I walked this route through the Index: ${summary}`,240);$('#markRegion').value=lastRoute.at(-1).region;$('#markSigil').value=discovered.size?'seed':'spark';$('#markX').value=Math.floor(8+Math.random()*84);$('#markY').value=Math.floor(8+Math.random()*84);showCrosshair();updateIssueUrl();rememberComposerReading('Wayfinding route',lastRoute.map(r=>r.region).join(' → '));$('#copyStatus').textContent='Route copied into the composer; review it, then open GitHub to make it permanent.';location.hash='leave-mark'}

function showCrosshair(){const c=$('#crosshair');c.hidden=false;c.style.left=$('#markX').value+'%';c.style.top=$('#markY').value+'%'}
function particles(){const c=$('#particleField'),ctx=c.getContext('2d');let pts=[];function size(){c.width=innerWidth;c.height=innerHeight;pts=Array.from({length:Math.min(120,Math.floor(innerWidth/10))},()=>({x:Math.random()*c.width,y:Math.random()*c.height,v:0.2+Math.random()*0.5,r:Math.random()*1.8}))}function draw(){ctx.clearRect(0,0,c.width,c.height);ctx.fillStyle='#7df9ff88';pts.forEach(p=>{p.y-=p.v;if(p.y<0)p.y=c.height;ctx.beginPath();ctx.arc(p.x,p.y,p.r,0,7);ctx.fill()});requestAnimationFrame(draw)}addEventListener('resize',size);size();if(!matchMedia('(prefers-reduced-motion: reduce)').matches)draw()}
$$('.region-button,.island').forEach(b=>b.addEventListener('click',()=>setRegion(b.dataset.region)));$('#pulseScan').onclick=()=>renderFragments(true);$('#makeRoute').onclick=generateRoute;$('#routeToMark').onclick=routeToComposer;$('#refreshWeather').onclick=updateAtlasWeather;$('#weatherToMark').onclick=weatherToComposer;$('#combineFragments').onclick=makeCrossReference;$('#crossToMark').onclick=crossReferenceToComposer;$('#clearInspector').onclick=clearInspector;renderInventory();initComposer();initFilters();initFieldNotes();initCatalogDrawers();initAnnexes();setRegion('Atrium');loadMarks();particles();
